name: Build for Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Rust'u kur
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Derle (Release)
        run: cargo build --release

      - name: ZIP'e paketle
        run: |
          cd target/release
          powershell Compress-Archive -Path neuroshield.exe -DestinationPath NeuroShield-Windows.zip
          move NeuroShield-Windows.zip $env:GITHUB_WORKSPACE

      - name: Yayınla (GitHub Release)
        uses: softprops/action-gh-release@v1
        with:
          files: NeuroShield-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

